#define _GNU_SOURCE
#include <stdlib.h>
#include <string.h>
#include "cpu.h"

static const cpu_t items[] =
{
  {
    .name = "EPYC 7373X",
    .codename = "Milan-X",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 3.05, .max = 3.8 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 768 },
    .thermalDesignPower = { .unit = "watts", .value = 240 },
    .released = "2022-03-22"
  },
  {
    .name = "EPYC 7473X",
    .codename = "Milan-X",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.8, .max = 3.7 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 768 },
    .thermalDesignPower = { .unit = "watts", .value = 240 },
    .released = "2022-03-22"
  },
  {
    .name = "EPYC 7543",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.8, .max = 3.7 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7573X",
    .codename = "Milan-X",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.8, .max = 3.6 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 768 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-22"
  },
  {
    .name = "EPYC 75F3",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.95, .max = 4 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7643",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 96, .physical = 48 },
    .speed = { .min = 2.3, .max = 3.6 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7663",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 112, .physical = 56 },
    .speed = { .min = 2, .max = 3.5 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 240 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7713",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 128, .physical = 64 },
    .speed = { .min = 2, .max = 3.675 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7713P",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 128, .physical = 64 },
    .speed = { .min = 2, .max = 3.675 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7763",
    .codename = "Milan",
    .architecture = "x86_64",
    .cores = { .total = 128, .physical = 64 },
    .speed = { .min = 2.45, .max = 3.5 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2021-03-15"
  },
  {
    .name = "EPYC 7773X",
    .codename = "Milan-X",
    .architecture = "x86_64",
    .cores = { .total = 128, .physical = 64 },
    .speed = { .min = 2.2, .max = 3.5 },
    .socket = "SP3",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 768 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-22"
  },
  {
    .name = "Ryzen 3 4100",
    .codename = "Renoir",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.8, .max = 4 },
    .socket = "AM4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-04-04"
  },
  {
    .name = "Ryzen 5 4500",
    .codename = "Renoir",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.6, .max = 4.1 },
    .socket = "AM4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-04-04"
  },
  {
    .name = "Ryzen 5 5500",
    .codename = "Cezanne",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.6, .max = 4.2 },
    .socket = "AM4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-04-04"
  },
  {
    .name = "Ryzen 5 5600",
    .codename = "Vermeer",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.5, .max = 4.4 },
    .socket = "AM4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 32 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-04-20"
  },
  {
    .name = "Ryzen 7 5700X",
    .codename = "Vermeer",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.4, .max = 4.6 },
    .socket = "AM4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 32 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-04-04"
  },
  {
    .name = "Ryzen 7 5800X3D",
    .codename = "Vermeer",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.4, .max = 4.5 },
    .socket = "AM4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 96 },
    .thermalDesignPower = { .unit = "watts", .value = 105 },
    .released = "2022-04-20"
  },
  {
    .name = "Ryzen Threadripper 5990X",
    .codename = "Chagall",
    .architecture = "x86_64",
    .cores = { .total = 128, .physical = 64 },
    .speed = { .min = 2.5, .max = 4.45 },
    .socket = "TRX4",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = NULL
  },
  {
    .name = "Ryzen Threadripper PRO 5945WX",
    .codename = "Chagall PRO",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 12 },
    .speed = { .min = 4.1, .max = 4.5 },
    .socket = "WRX8",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 64 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-08"
  },
  {
    .name = "Ryzen Threadripper PRO 5955WX",
    .codename = "Chagall PRO",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 4, .max = 4.5 },
    .socket = "WRX8",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 64 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-08"
  },
  {
    .name = "Ryzen Threadripper PRO 5965WX",
    .codename = "Chagall PRO",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 3.8, .max = 4.5 },
    .socket = "WRX8",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 128 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-08"
  },
  {
    .name = "Ryzen Threadripper PRO 5975WX",
    .codename = "Chagall PRO",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 3.6, .max = 4.5 },
    .socket = "WRX8",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 128 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-08"
  },
  {
    .name = "Ryzen Threadripper PRO 5995WX",
    .codename = "Chagall PRO",
    .architecture = "x86_64",
    .cores = { .total = 128, .physical = 64 },
    .speed = { .min = 2.7, .max = 4.5 },
    .socket = "WRX8",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 256 },
    .thermalDesignPower = { .unit = "watts", .value = 280 },
    .released = "2022-03-08"
  },
  {
    .name = "Core i3-10105F",
    .codename = "Comet Lake-R",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.7, .max = 4.4 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 6 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i3-12100F",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.3, .max = 4.3 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 58 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i5-11400F",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.6, .max = 4.4 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i5-11600",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.8, .max = 4.8 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i5-11600KF",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.9, .max = 4.9 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i5-12400F",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.5, .max = 4.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i5-12490F",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3, .max = 4.6 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 20 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022"
  },
  {
    .name = "Core i5-12600KF",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 10 },
    .speed = { .min = 3.7, .max = 4.9 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 20 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2021-11-04"
  },
  {
    .name = "Core i5-13600KF",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 3.5, .max = 5.1 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022-09-27"
  },
  {
    .name = "Core i7-11700F",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2.5, .max = 4.9 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i7-11700KF",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.6, .max = 5 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i7-12700F",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 12 },
    .speed = { .min = 3.3, .max = 4.9 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i7-12700KF",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 12 },
    .speed = { .min = 3.6, .max = 5 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2021-11-04"
  },
  {
    .name = "Core i7-13700KF",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 3.4, .max = 5.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022-09-27"
  },
  {
    .name = "Core i9-11900F",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2.5, .max = 5.2 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i9-11900KF",
    .codename = "Rocket Lake",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.5, .max = 5.3 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2021-03-16"
  },
  {
    .name = "Core i9-12900F",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2.4, .max = 5.1 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12900KF",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 3.2, .max = 5.2 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2021-11-04"
  },
  {
    .name = "Core i9-13900KF",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 24 },
    .speed = { .min = 3, .max = 5.8 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022-09-27"
  },
  {
    .name = "Xeon E-2314",
    .codename = "Rocket Lake-E",
    .architecture = "x86_64",
    .cores = { .total = 4, .physical = 4 },
    .speed = { .min = 2.8, .max = 4.5 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-09-08"
  },
  {
    .name = "Xeon E-2334",
    .codename = "Rocket Lake-E",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.4, .max = 4.8 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-09-08"
  },
  {
    .name = "Xeon E-2336",
    .codename = "Rocket Lake-E",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.9, .max = 4.8 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-09-08"
  },
  {
    .name = "Xeon E-2378",
    .codename = "Rocket Lake-E",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2.6, .max = 4.8 },
    .socket = "1200",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2021-09-08"
  },
  {
    .name = "Xeon Gold 5315Y",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.2, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 140 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5317",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 12 },
    .speed = { .min = 3, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5318H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 36, .physical = 18 },
    .speed = { .min = 2.5, .max = 3.8 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 24.75 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5318N",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.1, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5318S",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.1, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5318Y",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.1, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5320",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 52, .physical = 26 },
    .speed = { .min = 2.2, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 39 },
    .thermalDesignPower = { .unit = "watts", .value = 185 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5320H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 40, .physical = 20 },
    .speed = { .min = 2.4, .max = 4.2 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 27.5 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 5320T",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 40, .physical = 20 },
    .speed = { .min = 2.3, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6312U",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.4, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 185 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6314U",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.3, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6326",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 2.9, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 185 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6328H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 2.8, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 22 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6328HL",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 2.8, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 22 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6330",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 56, .physical = 28 },
    .speed = { .min = 2, .max = 3.1 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 42 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6330H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2, .max = 3.7 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 33 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6334",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.6, .max = 3.7 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6336Y",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.4, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 185 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6338N",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.2, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 185 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6338T",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.1, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6342",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.8, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 230 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6346",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 3.1, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6348",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 56, .physical = 28 },
    .speed = { .min = 2.6, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 42 },
    .thermalDesignPower = { .unit = "watts", .value = 235 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6348H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 2.3, .max = 4.2 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 33 },
    .thermalDesignPower = { .unit = "watts", .value = 165 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Gold 6354",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 36, .physical = 18 },
    .speed = { .min = 3, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 39 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8351N",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 72, .physical = 36 },
    .speed = { .min = 2.4, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 54 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8352M",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.3, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 185 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8352S",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.2, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8352V",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 72, .physical = 36 },
    .speed = { .min = 2.5, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 54 },
    .thermalDesignPower = { .unit = "watts", .value = 195 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8353H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 36, .physical = 18 },
    .speed = { .min = 2.5, .max = 3.8 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 24.75 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8354H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 36, .physical = 18 },
    .speed = { .min = 3.1, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 24.75 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8356H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.9, .max = 4.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 35.75 },
    .thermalDesignPower = { .unit = "watts", .value = 190 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8358",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.6, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 250 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8358P",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.6, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 240 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8360H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 3, .max = 4.2 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 33 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8360HL",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 3, .max = 4.2 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 33 },
    .thermalDesignPower = { .unit = "watts", .value = 225 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8360Y",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 72, .physical = 36 },
    .speed = { .min = 2.4, .max = 3.5 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 54 },
    .thermalDesignPower = { .unit = "watts", .value = 250 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8362",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.8, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 265 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8368",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 76, .physical = 38 },
    .speed = { .min = 2.4, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 57 },
    .thermalDesignPower = { .unit = "watts", .value = 270 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8368Q",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 76, .physical = 38 },
    .speed = { .min = 2.6, .max = 3.7 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 57 },
    .thermalDesignPower = { .unit = "watts", .value = 270 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8376H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 56, .physical = 28 },
    .speed = { .min = 2.6, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 38.5 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8376HL",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 56, .physical = 28 },
    .speed = { .min = 2.6, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 38.5 },
    .thermalDesignPower = { .unit = "watts", .value = 205 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8380",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 80, .physical = 40 },
    .speed = { .min = 2.3, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 60 },
    .thermalDesignPower = { .unit = "watts", .value = 270 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8380H",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 56, .physical = 28 },
    .speed = { .min = 2.9, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 38.5 },
    .thermalDesignPower = { .unit = "watts", .value = 250 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Platinum 8380HL",
    .codename = "Cooper Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 56, .physical = 28 },
    .speed = { .min = 2.9, .max = 4.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 14 },
    .cacheL3 = { .unit = "MB", .size = 38.5 },
    .thermalDesignPower = { .unit = "watts", .value = 250 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Silver 4309Y",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2.8, .max = 3.6 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 105 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Silver 4310",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 12 },
    .speed = { .min = 2.1, .max = 3.3 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 120 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Silver 4310T",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 10 },
    .speed = { .min = 2.3, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 15 },
    .thermalDesignPower = { .unit = "watts", .value = 105 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Silver 4314",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 2.4, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 135 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon Silver 4316",
    .codename = "Ice Lake-SP",
    .architecture = "x86_64",
    .cores = { .total = 40, .physical = 20 },
    .speed = { .min = 2.3, .max = 3.4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2021-04-06"
  },
  {
    .name = "Xeon W-3323",
    .codename = "Ice Lake-W",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 12 },
    .speed = { .min = 3.5, .max = 4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 220 },
    .released = "2021-07-29"
  },
  {
    .name = "Xeon W-3335",
    .codename = "Ice Lake-W",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 3.4, .max = 4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 250 },
    .released = "2021-07-29"
  },
  {
    .name = "Xeon W-3345",
    .codename = "Ice Lake-W",
    .architecture = "x86_64",
    .cores = { .total = 48, .physical = 24 },
    .speed = { .min = 3, .max = 4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 250 },
    .released = "2021-07-29"
  },
  {
    .name = "Xeon W-3365",
    .codename = "Ice Lake-W",
    .architecture = "x86_64",
    .cores = { .total = 64, .physical = 32 },
    .speed = { .min = 2.7, .max = 4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 48 },
    .thermalDesignPower = { .unit = "watts", .value = 270 },
    .released = "2021-07-29"
  },
  {
    .name = "Xeon W-3375",
    .codename = "Ice Lake-W",
    .architecture = "x86_64",
    .cores = { .total = 76, .physical = 38 },
    .speed = { .min = 2.5, .max = 4 },
    .socket = "4189",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 57 },
    .thermalDesignPower = { .unit = "watts", .value = 270 },
    .released = "2021-07-29"
  },
  {
    .name = "Ryzen 3 5125C",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 4, .physical = 2 },
    .speed = { .min = 3, .max = 3 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-05-05"
  },
  {
    .name = "Ryzen 3 5425C",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 2.7, .max = 4.1 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-05-05"
  },
  {
    .name = "Ryzen 3 5425U",
    .codename = "Barcelo",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 2.7, .max = 4.1 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-01-06"
  },
  {
    .name = "Ryzen 3 PRO 5475U",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 2.7, .max = 4.1 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 5 5625C",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.3, .max = 4.3 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-05-05"
  },
  {
    .name = "Ryzen 5 5625U",
    .codename = "Barcelo",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.3, .max = 4.3 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-01-06"
  },
  {
    .name = "Ryzen 5 6600H",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.3, .max = 4.5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 5 6600HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.3, .max = 4.5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 5 6600U",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.9, .max = 4.5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 5 7600X",
    .codename = "Raphael",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 4.7, .max = 5.3 },
    .socket = "AM5",
    .technologyNode = { .unit = "nanometers", .value = 5 },
    .cacheL3 = { .unit = "MB", .size = 32 },
    .thermalDesignPower = { .unit = "watts", .value = 105 },
    .released = "2022-09-27"
  },
  {
    .name = "Ryzen 5 PRO 5675U",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.3, .max = 4.3 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 5 PRO 6650H",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.3, .max = 4.5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 5 PRO 6650HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 3.3, .max = 4.5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 5 PRO 6650U",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.9, .max = 4.5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 7 5825C",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2, .max = 4.5 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-05-05"
  },
  {
    .name = "Ryzen 7 5825U",
    .codename = "Barcelo",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2, .max = 4.5 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-01-06"
  },
  {
    .name = "Ryzen 7 6800H",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.2, .max = 4.7 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 7 6800HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.2, .max = 4.7 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 7 6800U",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2.7, .max = 4.7 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 7 7700X",
    .codename = "Raphael",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 4.5, .max = 5.4 },
    .socket = "AM5",
    .technologyNode = { .unit = "nanometers", .value = 5 },
    .cacheL3 = { .unit = "MB", .size = 32 },
    .thermalDesignPower = { .unit = "watts", .value = 105 },
    .released = "2022-09-27"
  },
  {
    .name = "Ryzen 7 PRO 5875U",
    .codename = "Cezanne-U",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2, .max = 4.5 },
    .socket = "FP6",
    .technologyNode = { .unit = "nanometers", .value = 7 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 7 PRO 6850H",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.2, .max = 4.7 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 7 PRO 6850HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.2, .max = 4.7 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 7 PRO 6850U",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 2.7, .max = 4.7 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 9 6900HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.3, .max = 4.9 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 9 6900HX",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.3, .max = 4.9 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 9 6980HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.3, .max = 5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 9 6980HX",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.3, .max = 5 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Ryzen 9 7900X",
    .codename = "Raphael",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 12 },
    .speed = { .min = 4.7, .max = 5.6 },
    .socket = "AM5",
    .technologyNode = { .unit = "nanometers", .value = 5 },
    .cacheL3 = { .unit = "MB", .size = 64 },
    .thermalDesignPower = { .unit = "watts", .value = 170 },
    .released = "2022-09-27"
  },
  {
    .name = "Ryzen 9 7950X",
    .codename = "Raphael",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 16 },
    .speed = { .min = 4.5, .max = 5.7 },
    .socket = "AM5",
    .technologyNode = { .unit = "nanometers", .value = 5 },
    .cacheL3 = { .unit = "MB", .size = 64 },
    .thermalDesignPower = { .unit = "watts", .value = 170 },
    .released = "2022-09-27"
  },
  {
    .name = "Ryzen 9 PRO 6950H",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.3, .max = 4.9 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-04-19"
  },
  {
    .name = "Ryzen 9 PRO 6950HS",
    .codename = "Rembrandt",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 8 },
    .speed = { .min = 3.3, .max = 4.9 },
    .socket = "FP7",
    .technologyNode = { .unit = "nanometers", .value = 6 },
    .cacheL3 = { .unit = "MB", .size = 16 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-04-19"
  },
  {
    .name = "Celeron 7300",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 6, .physical = 5 },
    .speed = { .min = 1, .max = 1 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Celeron 7305",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 6, .physical = 5 },
    .speed = { .min = 1.1, .max = 1.1 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Celeron G6900",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 2, .physical = 2 },
    .speed = { .min = 3.4, .max = 3.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 4 },
    .thermalDesignPower = { .unit = "watts", .value = 46 },
    .released = "2022-01-04"
  },
  {
    .name = "Celeron G6900E",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 2, .physical = 2 },
    .speed = { .min = 3, .max = 3 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 4 },
    .thermalDesignPower = { .unit = "watts", .value = 46 },
    .released = "2022-01-04"
  },
  {
    .name = "Celeron G6900T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 2, .physical = 2 },
    .speed = { .min = 2.8, .max = 2.8 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 4 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-04"
  },
  {
    .name = "Celeron G6900TE",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 2, .physical = 2 },
    .speed = { .min = 2.4, .max = 2.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 4 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i3-12100",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.3, .max = 4.3 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 60 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i3-12100E",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.2, .max = 4.2 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 60 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i3-12100T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 2.2, .max = 4.1 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i3-12100TE",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 2.1, .max = 4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i3-1210U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 6 },
    .speed = { .min = 1, .max = 4.4 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 10 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i3-1215U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 6 },
    .speed = { .min = 1.2, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 10 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i3-1215U (IPU)",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 6 },
    .speed = { .min = 1.2, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 10 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i3-1220P",
    .codename = "Alder Lake-P",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.5, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 28 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i3-12300",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 3.5, .max = 4.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 60 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i3-12300HE",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 8 },
    .speed = { .min = 1.9, .max = 4.3 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i3-12300T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 8, .physical = 4 },
    .speed = { .min = 2.3, .max = 4.2 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i5-1230U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1, .max = 4.4 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-1235U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.3, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-1235U (IPU)",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.3, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-12400",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 2.5, .max = 4.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i5-12400T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 6 },
    .speed = { .min = 1.8, .max = 4.2 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i5-1240P",
    .codename = "Alder Lake-P",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 1.7, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 28 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-1240U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.1, .max = 4.4 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-12450H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 8 },
    .speed = { .min = 2, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i5-12450HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 8 },
    .speed = { .min = 2.4, .max = 4.4 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i5-1245U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.6, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-12500H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 2.5, .max = 4.5 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i5-1250P",
    .codename = "Alder Lake-P",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 1.7, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 28 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i5-12600H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 2.7, .max = 4.5 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i5-12600HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 2.5, .max = 4.6 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i5-13500",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 10 },
    .speed = { .min = 2.5, .max = 4.6 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 20 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022"
  },
  {
    .name = "Core i5-13600K",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 3.5, .max = 5.1 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022-09-27"
  },
  {
    .name = "Core i7-1250U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.1, .max = 4.7 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-1255U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.7, .max = 4.7 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-1260P",
    .codename = "Alder Lake-P",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 2.1, .max = 4.7 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 28 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-1260U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.1, .max = 4.7 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-12650H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 10 },
    .speed = { .min = 2.3, .max = 4.7 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-12650HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 2, .max = 4.7 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i7-1265U",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 12, .physical = 10 },
    .speed = { .min = 1.8, .max = 4.8 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 12 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-12700E",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 12 },
    .speed = { .min = 2.1, .max = 4.8 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-12700H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 2.3, .max = 4.7 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-12700T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 12 },
    .speed = { .min = 1.4, .max = 4.7 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-12700TE",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 12 },
    .speed = { .min = 1.4, .max = 4.6 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-1270P",
    .codename = "Alder Lake-P",
    .architecture = "x86_64",
    .cores = { .total = 16, .physical = 12 },
    .speed = { .min = 2.2, .max = 4.8 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 18 },
    .thermalDesignPower = { .unit = "watts", .value = 28 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-12800H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 2.4, .max = 4.8 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-12800HE",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 2.4, .max = 4.6 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-01"
  },
  {
    .name = "Core i7-12800HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2, .max = 4.8 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i7-1280P",
    .codename = "Alder Lake-P",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 1.8, .max = 4.8 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 28 },
    .released = "2022-02-23"
  },
  {
    .name = "Core i7-12850HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2.1, .max = 4.8 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 25 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i7-13700K",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 3.4, .max = 5.4 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022-09-27"
  },
  {
    .name = "Core i9-12900",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2.4, .max = 5.1 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12900E",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2.3, .max = 5 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 65 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12900H",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 2.5, .max = 5 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12900HK",
    .codename = "Alder Lake-H",
    .architecture = "x86_64",
    .cores = { .total = 20, .physical = 14 },
    .speed = { .min = 2.5, .max = 5 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 24 },
    .thermalDesignPower = { .unit = "watts", .value = 45 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12900HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2.3, .max = 5 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i9-12900KS",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 3.4, .max = 5.5 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 150 },
    .released = "2022-04-05"
  },
  {
    .name = "Core i9-12900T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 1.4, .max = 4.9 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12900TE",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 1.1, .max = 4.8 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-04"
  },
  {
    .name = "Core i9-12950HX",
    .codename = "Alder Lake-HX",
    .architecture = "x86_64",
    .cores = { .total = 24, .physical = 16 },
    .speed = { .min = 2.3, .max = 5 },
    .socket = "BGA 1964",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 30 },
    .thermalDesignPower = { .unit = "watts", .value = 55 },
    .released = "2022-05-10"
  },
  {
    .name = "Core i9-13900",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 24 },
    .speed = { .min = 2, .max = 5.6 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022"
  },
  {
    .name = "Core i9-13900K",
    .codename = "Raptor Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 32, .physical = 24 },
    .speed = { .min = 3, .max = 5.8 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 36 },
    .thermalDesignPower = { .unit = "watts", .value = 125 },
    .released = "2022-09-27"
  },
  {
    .name = "Pentium 8500",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 6, .physical = 5 },
    .speed = { .min = 1, .max = 4.4 },
    .socket = "BGA 1781",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 9 },
    .released = "2022-02-23"
  },
  {
    .name = "Pentium 8505",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 6, .physical = 5 },
    .speed = { .min = 1.2, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Pentium 8505 (IPU)",
    .codename = "Alder Lake-U",
    .architecture = "x86_64",
    .cores = { .total = 6, .physical = 5 },
    .speed = { .min = 1.2, .max = 4.4 },
    .socket = "BGA 1744",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 8 },
    .thermalDesignPower = { .unit = "watts", .value = 15 },
    .released = "2022-02-23"
  },
  {
    .name = "Pentium Gold G7400",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 4, .physical = 2 },
    .speed = { .min = 3.7, .max = 3.7 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 6 },
    .thermalDesignPower = { .unit = "watts", .value = 46 },
    .released = "2022-01-04"
  },
  {
    .name = "Pentium Gold G7400E",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 4, .physical = 2 },
    .speed = { .min = 3.6, .max = 3.6 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 6 },
    .thermalDesignPower = { .unit = "watts", .value = 46 },
    .released = "2022-01-04"
  },
  {
    .name = "Pentium Gold G7400T",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 4, .physical = 2 },
    .speed = { .min = 3.1, .max = 3.1 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 6 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-04"
  },
  {
    .name = "Pentium Gold G7400TE",
    .codename = "Alder Lake-S",
    .architecture = "x86_64",
    .cores = { .total = 4, .physical = 2 },
    .speed = { .min = 3, .max = 3 },
    .socket = "1700",
    .technologyNode = { .unit = "nanometers", .value = 10 },
    .cacheL3 = { .unit = "MB", .size = 6 },
    .thermalDesignPower = { .unit = "watts", .value = 35 },
    .released = "2022-01-04"
  }
};

#define NUM_CPU_ITEMS (sizeof(items) / sizeof(cpu_t))

const cpu_t *cpu_find_by_fuzzy_name(char *name)
{
  long unsigned i;
  for(i = 0; i < NUM_CPU_ITEMS; i++)
    if(strcasestr(items[i].name, name) != NULL)
      return &items[i];
  return NULL;
}

const cpu_t *cpu_find_by_exact_name(char *name)
{
  long unsigned i;
  for(i = 0; i < NUM_CPU_ITEMS; i++)
    if(strcmp(items[i].name, name) == 0)
      return &items[i];
  return NULL;
}

const cpu_t *cpu_find_by_fuzzy_codename(char *codename)
{
  long unsigned i;
  for(i = 0; i < NUM_CPU_ITEMS; i++)
    if(strcasestr(items[i].codename, codename) != NULL)
      return &items[i];
  return NULL;
}

const cpu_t *cpu_find_by_exact_codename(char *codename)
{
  long unsigned i;
  for(i = 0; i < NUM_CPU_ITEMS; i++)
    if(strcmp(items[i].codename, codename) == 0)
      return &items[i];
  return NULL;
}